# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  schedule: ## Schedule the job to run at 12.am daily.
    - cron: '0 0 * * *'


jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: swift-actions/setup-swift@v1
    - uses: actions/checkout@v3
    - name: Build
      run: swift run DenBlocklists $PWD/blocklists.json $PWD/Output
    - name: Deploy
      run: git subtree split --prefix Output -b gh-pages && git push -f origin gh-pages:gh-pages && git branch -D gh-pages
